polyclinic/cardfile/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^doctors/(?P<stub>[-\w]+)$', views.DoctorListView.as_view(), name='doctors'),
    url(r'^doctors/detail/(?P<pk>\d+)$', views.DoctorDetailView.as_view(), name='doctor-detail'),
    url(r'^pacients/(?P<stub>[-\w]+)$', views.PacientListView.as_view(), name='pacients'),
    url(r'^pacients/detail/(?P<pk>\d+)$', views.PacientDetailView.as_view(), name='pacient-detail'),
    url(r'^pacients/detail/(?P<pk>\d+)/update/$', views.PacientUpdate.as_view(), name='pacient_update'),
    url(r'^pacients/create/$', views.PacientCreate.as_view(), name='pacient_create'),
    url(r'^treatmenthistory/(?P<stub>[-\w]+)$', views.TreatmentHistoryListView.as_view(), name='treatment_history'),  
    url(r'^treatmenthistory/detail/(?P<pk>\d+)$', views.HistoryDetailView, name='treatment_history_detail'), 
    url(r'^treatmenthistory/detail/(?P<pk>\d+)/update/$', views.TreatmentHistoryUpdate.as_view(), name='treatment_history_update'),  
    url(r'^treatmenthistory/create/$', views.TreatmentHistoryCreate.as_view(), name='treatment_create'),
    #url(r'^treatmenthistory/detail/(?P<pk>\d+)$', views.TreatmentDetailView.as_view(), name='treatment_history_detail'),  
    
    
]

polyclinic/polyclinic/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cardfile/', include('cardfile.urls')),
    path('', RedirectView.as_view(url='/cardfile/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')), 
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polyclinic/cardfile/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
import uuid

# Create your models here.

class Doctors_specialty(models.Model):
    """
    Модель, представляющая специальность врача (терапевт, невропатолог и т.п.)
    """
    specialty = models.CharField(
        verbose_name='Специальность',
        max_length=200, 
        help_text="Введите специальность врача (терапевт, невропатолог и т.п.)")  

    class Meta:
        verbose_name='Специальность врача'  
        verbose_name_plural = 'Специальности врачей'    

    def __str__(self):
        return self.specialty

class Social_status(models.Model):
    """
    Модель, представляющая социальный статус пациента (учащийся, работающий, временно неработающий, инвалид, пенсионер)
    """
    status = models.CharField(
        verbose_name='Социальный статус:',
        max_length=200, 
        help_text="Введите социальный статус пациента (учащийся, работающий, временно неработающий, инвалид, пенсионер)")

    class Meta:
        verbose_name='Социальный статус пациента'
        verbose_name_plural = 'Социальные статусы пациентов' 

    def __str__(self):
        return self.status

class Diagnosis(models.Model):
    """
    Модель, представляющая диагноз (кариес, астма, пневмония и т.д.)
    """
    diagnosis = models.CharField(
        verbose_name='Диагноз',
        max_length=200, 
        help_text="Введите диагноз (кариес, астма, пневмония и т.д.)")

    class Meta:
        verbose_name='Диагноз'
        verbose_name_plural = 'Диагнозы' 

    def __str__(self):
        return self.diagnosis

class Pacient(models.Model):
    """
    Модель, представляющая пациента
    """
    name = models.CharField(
        verbose_name='ФИО пациента',
        max_length=200)

    date_of_birth = models.DateField(
        verbose_name='Дата рожения пациента',
        null=True, 
        blank=True)

    soc_status = models.ForeignKey(
        'Social_status',
        verbose_name='Социальный статус пациента', 
        on_delete=models.SET_NULL,
        null=True)

    PACIENT_CONDITION = (
        ('t', 'лечится'),
        ('c', 'вылечился'),
        ('h', 'направлен в стационар'),
        ('d', 'умер'),
    )

    condition = models.CharField(
        verbose_name='Состояние пациента',
        max_length=1, 
        choices=PACIENT_CONDITION, 
        blank=True, default='t')        

    date_of_death = models.DateField(
        verbose_name='Дата смерти пациента',
        null=True,
        blank=True,
        help_text='(необязательно)')

    class Meta:
        ordering = ['name']
        verbose_name='Пациент'
        verbose_name_plural = 'Пациенты' 

    def get_absolute_url(self):
        return reverse('pacient-detail', args=[str(self.id)])


    def __str__(self):
        return self.name

class Doctor(models.Model):
    """
    Модель, представляющая врача
    """
    name = models.CharField(
        verbose_name='ФИО врача',
        max_length=200) 

    user = models.ForeignKey(
        User,
        verbose_name='Username врача', 
        on_delete=models.SET_NULL,
        null=True)

    QUALIFICATION_LEVEL = (
        ('2', 'Вторая квалификационная категория'),
        ('1', 'Первая квалификационная категория'),
        ('0', 'Высшая квалификационная категория'),
    )

    qualification = models.CharField(
        verbose_name='Квалификация врача',
        max_length=1, 
        choices=QUALIFICATION_LEVEL, 
        blank=True,
        default='2') 

    doc_specialty = models.ForeignKey(
        'Doctors_specialty',
        verbose_name='Специальность врача', 
        on_delete=models.SET_NULL,
        null=True) 
    
    class Meta:
        ordering = ['doc_specialty']
        verbose_name='Врач'
        verbose_name_plural = 'Врачи' 
        permissions = (("can_add_doctor", "Can add doctor"),)

    def get_absolute_url(self):
        return reverse('doctor-detail', args=[str(self.id)])


    def __str__(self):
        return '{0} ({1} - {2})'.format(self.name, self.doc_specialty, self.QUALIFICATION_LEVEL[2-int(self.qualification)][1])

class Treatment_history(models.Model):
    """
    Модель, представляющая историю лечений пациентов
    """

    pac_name = models.ForeignKey(
        'Pacient',
        verbose_name='Пациент',
        on_delete=models.SET_NULL,
        null=True)  

    doc_name = models.ForeignKey(
        'Doctor', 
        verbose_name='Лечащий врач',
        on_delete=models.SET_NULL,
        null=True) 

    diagnosis = models.ForeignKey(
        'Diagnosis', 
        verbose_name='Диагноз',
        on_delete=models.SET_NULL,
        null=True) 

    description = models.TextField(
        verbose_name='Симптомы',
        max_length=1000)

    ambulatory = models.BooleanField(verbose_name='Амбулаторное лечение')

    dispensary = models.BooleanField(verbose_name='Диспансерный учет')

    start_date_of_treatment = models.DateField(
        verbose_name='Дата начала лечения',
        null=True,
        blank=True)

    end_date_of_treatment = models.DateField(
        verbose_name='Дата окончания лечения',
        null=True,
        blank=True)
    
    class Meta:
        ordering = ['start_date_of_treatment']
        verbose_name='История лечения'
        verbose_name_plural = 'Истории лечений'

    def get_absolute_url(self):
        return reverse('treatment_history_detail', args=[str(self.id)])


    def __str__(self):
        return '{0} : {1} ({2})'.format(self.start_date_of_treatment, self.pac_name.name, self.diagnosis)

polyclinic/cardfile/views.py
from django.shortcuts import render
from .models import Doctors_specialty, Social_status, Diagnosis, Pacient, Doctor, Treatment_history
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView 
import datetime

def index(request):
    return render(
        request,
        'index.html',
        context={}
    )

class DoctorListView(generic.ListView):
    model = Doctor
    paginate_by = 20

    def get_queryset(self, queryset=None):
        try:   
            href = str(self.kwargs['stub'])         
            if href == 'all' or href == 'a_ll':
                return Doctor.objects.all()
            elif href.split('_')[0] == 'a':
                return Doctor.objects.filter(doc_specialty__exact=href.split('_')[1]).order_by('name')
            elif href.split('_')[1] == 'll':
                return Doctor.objects.filter(qualification__exact=href.split('_')[0]).order_by('name')
            else:
                return Doctor.objects.filter(qualification__exact=href.split('_')[0]).filter(doc_specialty__exact=href.split('_')[1]).order_by('name')            
        except Doctor.DoesNotExist:
            raise Http404("Такого фильтра не существует")

class DoctorDetailView(generic.DetailView):
    model = Doctor

    def doc_detail_view(self, request, pk):
        try:
            doc_id=Doctor.objects.get(pk=pk)
        except Doctor.DoesNotExist:
            raise Http404("Doctor does not exist")

        return render(
            request,
            'cardfile/doctor_detail.html',
            context={'doc':doc_id,}
        )

class PacientListView(generic.ListView):
    model = Pacient
    paginate_by = 20

    def get_queryset(self, queryset=None):
        try:
            if self.kwargs['stub'] == 'all':
                return Pacient.objects.all().order_by('name')
            else:
                return Pacient.objects.filter(condition__exact=self.kwargs['stub']).order_by('name')
        except Pacient.DoesNotExist:
            raise Http404("Такого фильтра не существует")

class PacientDetailView(generic.DetailView):
    model = Pacient

    def pac_detail_view(self, request, pk):
        try:
            pac_id=Pacient.objects.get(pk=pk)
        except Pacient.DoesNotExist:
            raise Http404("Pacient does not exist")

        return render(
            request,
            'cardfile/pacient_detail.html',
            context={'pac':pac_id,}
        )

class TreatmentHistoryListView(generic.ListView):
    model = Treatment_history
    paginate_by = 20

    def get_queryset(self, queryset=None):  
        try:
            if self.kwargs['stub'] == 'all':
                return Treatment_history.objects.all()
            elif self.kwargs['stub'] == 'my':
                try:
                    return Treatment_history.objects.filter(doc_name=Doctor.objects.filter(user=self.request.user)[0].id) 
                except:
                    return Treatment_history.objects.filter(pk=-1)
            else: 
                return Treatment_history.objects.filter(diagnosis__exact=self.kwargs['stub'])
        except Treatment_history.DoesNotExist:
            raise Http404("Такого фильтра не существует")      

class TreatmentDetailView(generic.DetailView):
    model = Treatment_history

    def pac_detail_view(self, request, pk):
        print('*********************************************')
        try:
            hist_id=Treatment_history.objects.get(pk=1) #1 - для теста
        except Treatment_history.DoesNotExist:
            raise Http404("Записи не существует")

        return render(
            request,
            'cardfile/treatment_history_detail.html',
            context={'hist':hist_id,}
        )


def HistoryDetailView(request, pk):
    print('=================================================')
    try:
        hist_id=Treatment_history.objects.get(pk=pk)
    except Treatment_history.DoesNotExist:
        raise Http404("Записи не существует")
    return render(
        request,
        'cardfile/treatment_history_detail.html',
        context={'hist': hist_id ,}
    )


class PacientCreate(CreateView):
    model = Pacient
    fields = '__all__'    

class PacientUpdate(UpdateView):
    model = Pacient
    fields = '__all__'

class TreatmentHistoryCreate(CreateView):
    model = Treatment_history
    fields = '__all__'
    initial={'start_date_of_treatment': datetime.date.today(),}
    

class TreatmentHistoryUpdate(UpdateView):
    model = Treatment_history
    fields = '__all__'

polyclinic/cardfile/templates/cardfile/doctor_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}
  <h1>{{ doctor.name }}</h1>
  {{doctor.doc_specialty}},
  {% if doctor.qualification == '0' %}
    высшая квалификационная категория
  {% elif doctor.qualification == '1' %}
    первая квалификационная категория
  {% elif doctor.qualification == '2' %}
    вторая квалификационная категория
  {% endif %}
  <div style="margin-left:20px;margin-top:20px">
    <h4>История пациентов</h4>
    {% for copy in doctor.treatment_history_set.all %}
      <hr>
      <p><strong><a href="{% url 'treatment_history_detail' copy.pk %}">{{copy}}</a></strong></p>   
    {% endfor %}
  </div>
  <a href="{% url 'doctors' 'all' %}">Вернуться</a>
{% else %}
  <meta http-equiv="refresh" content="1; URL={% url 'login'%}" />
{% endif %}
{% endblock %}

polyclinic/cardfile/templates/cardfile/doctor_list.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}
    <h1>Список врачей</h1>
    <div class="filter">
      <form>
        <select name="java-navigator" onchange="  
          var arrayOfStrings = window.location.href.split('/');         
          var hrefString = arrayOfStrings[arrayOfStrings.length-1];         
          if (hrefString == 'all') top.location.href = this.options[this.selectedIndex].value + '_ll';
          else top.location.href = this.options[this.selectedIndex].value + '_' + hrefString.split('_')[1];">
            <option value="">фильтр категорий</option>
            <option value="a">все</option>
            <option value="2">Вторая квалификационная категория</option>
            <option value="1">Первая квалификационная категория</option>
            <option value="0">Высшая квалификационная категория</option>
        </select>      
      </form>
      <form>
        <select name="java-navigator" onchange="
          var arrayOfStrings = window.location.href.split('/');         
          var hrefString = arrayOfStrings[arrayOfStrings.length-1];         
          if (hrefString == 'all') top.location.href = 'a_' + this.options[this.selectedIndex].value;
          else top.location.href = hrefString.split('_')[0] + '_' + this.options[this.selectedIndex].value;">
            <option value="">фильтр специальностей</option>
            <option value="ll">все</option>
            <option value="1">Хирург</option>
            <option value="2">Фельдшер</option>
            <option value="3">Терапевт</option>
            <option value="4">Стоматолог</option>
            <option value="5">Рентгенолог</option>
            <option value="6">Психотерапевт</option>
            <option value="7">Психиатр</option>
            <option value="8">Отоларинголог</option>
            <option value="9">Нарколог</option>
            <option value="10">Гинеколог</option>
            <option value="11">Педиатр</option>
        </select>      
      </form>
      <a href="{% url 'doctors' 'all' %}">сбросить фильтры</a>
    </div>
    {% if object_list %}
    <ul>

      {% for doc in object_list %}
      <li>
        <a href="{{ doc.get_absolute_url }}">{{ doc.name }}</a> ({{doc.doc_specialty}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Здесь нет ни одного врача</p>
    {% endif %}
{% else %}
  <meta http-equiv="refresh" content="1; URL={% url 'login'%}" />
{% endif %}
{% endblock %}

polyclinic/cardfile/templates/cardfile/pacient_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}
  <h1>{{ pacient }}</h1>  
  <a href="{% url 'pacient_update' pacient.pk %}">Изменить информацию о пациенте</a><br><br> 
  {{ pacient.date_of_birth }} 
    {% if pacient.date_of_death != None %} 
      - {{ pacient.date_of_death }} 
    {% endif %}<br>
  {{ pacient.soc_status }},
  {% if pacient.condition == 't' %}
    на лечении
  {% elif pacient.condition == 'c' %}
    здоров
  {% elif pacient.condition == 'h' %}
    направлен в стационар
  {% elif pacient.condition == 'd' %}
    мертв
  {% endif %}

  <div style="margin-left:20px;margin-top:20px">
    <h4>История болезней пациента</h4>
    {% for copy in pacient.treatment_history_set.all %}
      <hr>
      <p><strong><a href="{% url 'treatment_history_detail' copy.pk %}">{{copy}}</a></strong></p>      
    {% endfor %}
  </div>
  <a href="{% url 'pacients' 'all' %}">Вернуться</a>
{% else %}
  <meta http-equiv="refresh" content="1; URL={% url 'login'%}" />
{% endif %}
{% endblock %}

polyclinic/cardfile/templates/cardfile/pacient_form.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="AAA">
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Ок" />
    </form>  
    <a href="{% url 'pacients' 'all' %}">Вернуться</a>
</div>    
{% else %}
    <meta http-equiv="refresh" content="1; URL={% url 'login'%}" />
{% endif %}  
{% endblock %}

polyclinic/cardfile/templates/cardfile/pacient_list.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}
    <h1>Список пациентов</h1>    
    <div class="filter">
      <form>      
        <select name="java-navigator" onchange="top.location.href = this.options[this.selectedIndex].value;">
          <option value="">фильтр</option>
          <option value="all">Все</option>
          <option value="t">Лечится</option>
          <option value="c">Вылечился</option>
          <option value="h">Направлен в стационар</option>
          <option value="d">Умер</option>
        </select>      
      </form>
      <a href="{% url 'pacient_create' %}">Добавить пациента</a> 
    </div>
    {% if object_list %}
    <ul>

      {% for pac in object_list %}
      <li>
        <a href="{{ pac.get_absolute_url }}">{{ pac.name }}</a> 
        (
          {% if pac.condition == 't' %} лечится {% endif %} 
          {% if pac.condition == 'c' %} вылечился {% endif %} 
          {% if pac.condition == 'h' %} направлен в стационар {% endif %} 
          {% if pac.condition == 'd' %} умер {% endif %} 
        )
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Здесь нет ни одного пациента</p>
    {% endif %} 
{% else %}
  <meta http-equiv="refresh" content="1; URL={% url 'login'%}" />
{% endif %}  
{% endblock %}

polyclinic/cardfile/templates/cardfile/treatment_history_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}
  <h1>{{ hist }}</h1>
  <p><a href="{% url 'treatment_history_update' hist.pk %}">Изменить информацию о лечении</a></p>
  <hr>
  <div style="margin-left:20px;margin-top:20px">
    <p><strong>{{hist.start_date_of_treatment}}
      {% if hist.end_date_of_treatment != None %} 
        - {{ hist.end_date_of_treatment }} 
      {% endif %}</strong></p>     
    <p><strong>Пациент:</strong> <a href="{% url 'pacient-detail' hist.pac_name.pk %}">{{ hist.pac_name }}</a></p>
    <p><strong>Лечащий врач:</strong> <a href="{% url 'doctor-detail' hist.doc_name.pk %}">{{hist.doc_name}}</a></p>
    <p><strong>Диагноз:</strong> {{hist.diagnosis}}</p>
    <p><strong>Симптомы:</strong> {{hist.description}}</p>
    <p><strong>Амбулаторное лечение:</strong> 
      <abbr class="
        {% if hist.ambulatory == True %}
          text-success
        {% else %}
          text-danger
        {% endif %}">
        {% if hist.ambulatory == True %}
          Да
        {% else %}
          Нет
        {% endif %}
      </abbr></p>
    <p><strong>Диспансерный учет:</strong> 
      <abbr class="
        {% if hist.dispensary == True %}
          text-success
        {% else %}
          text-danger
        {% endif %}">
        {% if hist.dispensary == True %}
          Да
        {% else %}
          Нет
        {% endif %}
      </abbr></p>
    </div>
  <a href="{% url 'treatment_history' 'all'%}">Вернуться</a>
{% else %}
  <meta http-equiv="refresh" content="1; URL={% url 'login'%}" />
{% endif %} 
{% endblock %}

polyclinic/cardfile/templates/cardfile/treatment_history_form.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="AAA">
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Ок" />
    </form> 
    <a href="{% url 'treatment_history' 'all' %}">Вернуться</a>    
</div>
{% else %}
    <meta http-equiv="refresh" content="1; URL={% url 'login'%}" />
{% endif %}    
{% endblock %}

polyclinic/cardfile/templates/cardfile/treatment_history_list.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}
    <h1>История лечений</h1>
    <div class="filter">
      <form>      
        <select name="java-navigator" onchange="top.location.href = this.options[this.selectedIndex].value;">
          <option value="">фильтр</option>
          <option value="all">Все</option>
          <option value="my">Мои</option>
          <option value="1">Алкоголизм</option>
          <option value="2">Болезнь почек</option>
          <option value="3">Варикоз</option>
          <option value="4">Гайморит</option>
          <option value="5">Гастрит</option>
          <option value="6">Герпес</option>
          <option value="7">Дерматит</option>
          <option value="8">Диарея</option>
          <option value="9">Панкреатит</option>
          <option value="10">Пневмония</option>
          <option value="11">Свинка</option>
          <option value="12">Синдром Дауна</option>
          <option value="13">Хронический артрит</option>
          <option value="14">Хронический стресс</option>
          <option value="15">Хроническая стенокардия</option>
          <option value="16">Язвенная болезнь</option>
        </select>      
      </form>
      <a href="{% url 'treatment_create' %}">Добавить случай</a> 
    </div>
    {% if object_list %}
    <ul>
      {% for hist in object_list %}
      <li>
        <a href="{{ hist.get_absolute_url }}">{{hist}}</a>         
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Здесь нет ни одной записи</p>
    {% endif %}
{% else %}
  <meta http-equiv="refresh" content="1; URL={% url 'login'%}" />
{% endif %}   
{% endblock %}